include:
  - path: ./docker-compose-base.yml
    env_file: ./.env

services:
  ragflow:
    depends_on:
      mysql:
        condition: service_healthy
      es01:
        condition: service_healthy
    image: infiniflow/ragflow:${RAGFLOW_VERSION}
    platform: linux/amd64
    container_name: ragflow-server
    ports:
      - ${SVR_HTTP_PORT}:9380
      - 80:80
      - 443:443
    volumes:
      - ./service_conf.yaml:/ragflow/conf/service_conf.yaml
      - ./ragflow-logs:/ragflow/logs
      - ./nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # Mount specific folders from the parent ragflow directory using relative paths
      - ../api:/ragflow/api
      - ../conf:/ragflow/conf
      - ../rag:/ragflow/rag
      - ../graphrag:/ragflow/graphrag
      - ../agent:/ragflow/agent
      - ../deepdoc:/ragflow/deepdoc
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=https://huggingface.co
      - MACOS=${MACOS}
      - API_KEY=${API_KEY}
    networks:
      - ragflow
    restart: always
